Simple Governor OZ proposal
solidity-labs-io/fps-example-repo pull request #5
Opened 2024-05-24 03:43 UTC by prateek105

2024-05-24 12:44 UTC, anajuliabit requested changes

2024-05-24 12:44 UTC, anajuliabit commented on script/DeployGovernorOz.s.sol
> +        TimelockController timelock = new TimelockController(60, proposers, executors, dev);
let's pass an empty array for executors; this way, anyone is allowed to do it.

2024-05-24 12:44 UTC, anajuliabit commented on script/DeployGovernorOz.s.sol
> +        timelock.grantRole(keccak256("EXECUTOR_ROLE"), address(governor));
I think governor should only have the proposer role, and executor can be anyone. Also, revoke DEPLOYER_EOA proposer role

2024-05-24 12:44 UTC, anajuliabit commented on src/proposals/simple-vault-governor-oz/GovernorOZProposal_01.sol
> +        vm.selectFork(primaryForkId);
```suggestion
        setPrimaryFork(vm.createSelectFork("sepolia"));
```

2024-05-24 12:44 UTC, anajuliabit commented on src/proposals/simple-vault-governor-oz/GovernorOZProposal_01.sol
> +        vm.makePersistent(address(addresses));
no need to make persistent as this is not a cross chain proposal

2024-05-24 12:44 UTC, anajuliabit commented on src/proposals/simple-vault-governor-oz/GovernorOZProposal_01.sol
> +        /// CALLS -- mutative and recorded
move this comment above line 71 as whitelist is also recorded

2024-05-24 12:44 UTC, anajuliabit commented on src/proposals/simple-vault-governor-oz/GovernorOZProposal_02.sol
> +        vm.selectFork(primaryForkId);
simplify

2024-05-24 12:44 UTC, anajuliabit commented on src/proposals/simple-vault-governor-oz/GovernorOZProposal_02.sol
> +        vm.makePersistent(address(addresses));
remove

2024-05-24 12:44 UTC, anajuliabit commented on test/governor-oz/GovernorOZPostProposalCheck.sol
> +        vm.makePersistent(address(governorOZproposal));
no need to make persistent

2024-05-24 19:11 UTC, anajuliabit submitted a review, later dismissed
LGTM

2024-05-24 19:12 UTC, anajuliabit commented on script/DeployGovernorOz.s.sol
> +        TimelockController timelock = new TimelockController(60, proposers, executors, dev);
I don't see this addressed

2024-05-24 19:12 UTC, anajuliabit commented on script/DeployGovernorOz.s.sol
> +        timelock.grantRole(keccak256("EXECUTOR_ROLE"), address(governor));
I don't see this addressed

2024-05-27 04:28 UTC, ElliotFriedman commented on script/DeployGovernorOz.s.sol
> +        timelock.grantRole(keccak256("EXECUTOR_ROLE"), address(governor));
agreed address(0) should have executor or whatever the config is so that anyone can execute

2024-05-27 04:30 UTC, ElliotFriedman commented on script/DeployGovernorOz.s.sol
> +        TimelockController timelock = new TimelockController(60, proposers, executors, dev);
the only way that anyone can execute is if the executor address(0) has the executor role

<img width="709" alt="Screenshot 2024-05-27 at 12 30 03 AM" src="https://github.com/solidity-labs-io/fps-example-repo/assets/34463580/11f24243-f90a-4958-b1d3-75826aaa23a3">

<img width="955" alt="Screenshot 2024-05-27 at 12 30 21 AM" src="https://github.com/solidity-labs-io/fps-example-repo/assets/34463580/d9624060-4534-4d5f-81d5-8f8b89afedf4">

2024-05-27 04:30 UTC, ElliotFriedman commented on script/DeployGovernorOz.s.sol
> +        executors[0] = dev;
should be address(0)

2024-05-27 04:31 UTC, ElliotFriedman commented on script/DeployGovernorOz.s.sol
> +    function run() public virtual {
would be a really great use of fps if you could wrap this script up into two sections in a single proposal file:

1. deploy
2. validate

then run things on chain and ensure it is all deployed correctly

2024-05-27 18:25 UTC, prateek105 commented on script/DeployGovernorOz.s.sol
> +        TimelockController timelock = new TimelockController(60, proposers, executors, dev);
updated in [ddd7a2e](https://github.com/solidity-labs-io/fps-example-repo/pull/5/commits/ddd7a2e5637d28cf4865938ceb510a6fa10f7aa8)

2024-05-27 18:25 UTC, prateek105 commented on script/DeployGovernorOz.s.sol
> +        executors[0] = dev;
updated in [ddd7a2e](https://github.com/solidity-labs-io/fps-example-repo/pull/5/commits/ddd7a2e5637d28cf4865938ceb510a6fa10f7aa8)

2024-05-28 06:36 UTC, prateek105 commented on script/DeployGovernorOz.s.sol
> +    function run() public virtual {
I think fps should be used for proposals and as there are no actions to be made here, this does not look like a use case of fps to me. A simple script feels more suitable for this use case.

2024-06-10 12:14 UTC, prat-gpt commented on script/DeployGovernorOz.s.sol
> +    function run() public virtual {
updated here [126e468](https://github.com/solidity-labs-io/fps-example-repo/pull/5/commits/126e46820152d18854537cfa17887ac9881c4c4f)

2024-06-26 05:27 UTC, ElliotFriedman commented on script/DeployGovernorBravo.s.sol
> +    function validate() public override {
looks like we can make this function view

2024-06-26 05:27 UTC, ElliotFriedman commented on script/DeployTimelock.s.sol
> +    function validate() public override {
can we make this function view?

2024-06-26 05:30 UTC, ElliotFriedman commented on script/InitializeBravo.s.sol
>          address govAlpha = address(new MockGovernorAlpha());
let's do an isAddressSet check here before we create this new contract

2024-06-26 05:31 UTC, ElliotFriedman commented on src/mocks/governor-oz/MockGovernorOz.sol
> +import "@openzeppelin/governance/extensions/GovernorTimelockControl.sol";
style: import {ContractName} from ..

2024-06-26 05:31 UTC, ElliotFriedman commented on src/proposals/simple-vault-bravo/BravoProposal_02.sol
> -        vm.makePersistent(address(addresses));
is this done somewhere else?

2024-06-26 06:34 UTC, prateek105 commented on src/proposals/simple-vault-bravo/BravoProposal_02.sol
> -        vm.makePersistent(address(addresses));
removed from all the proposals as we have to persist only when there is a cross chain proposal.

2024-06-26 12:08 UTC, prateek105 commented on script/DeployGovernorBravo.s.sol
> +    function validate() public override {
Earlier I was unable to make this function view, it caused compilation error. It got fixed after I updated the forge-std submodule.

2024-06-26 12:08 UTC, prateek105 commented on script/DeployTimelock.s.sol
> +    function validate() public override {
Earlier I was unable to make this function view, it caused compilation error. It got fixed after I updated the forge-std submodule.

2024-06-27 06:23 UTC, ElliotFriedman approved these changes
LGTM!

2024-06-27 06:24 UTC, merged