add state diff proposal example
solidity-labs-io/fps-example-repo pull request #9
Opened 2024-07-30 15:30 UTC by prateek105

2024-08-01 19:33 UTC, anajuliabit requested changes

2024-08-01 19:33 UTC, anajuliabit commented on src/mocks/state-diff/TokenWrapper.sol
> +contract TokenWrapper is Ownable {
to avoid adding extra mocks to the repo you could use MockERC20Votes.sol

2024-08-01 19:33 UTC, anajuliabit commented on src/proposals/state-diff/StateDiffTimelockProposal_01.sol
instead of adding a new folder, could you please create a _03 proposal to simple-vault-timelock?

2024-08-05 11:42 UTC, prateek105 commented on src/mocks/state-diff/TokenWrapper.sol
> +contract TokenWrapper is Ownable {
I have made this contract so that there are both ETH and ERC20 token actions. I don't think `MockERC20Votes` involves any ETH transfers.

2024-08-05 11:46 UTC, prateek105 commented on src/proposals/state-diff/StateDiffTimelockProposal_01.sol
Two reasons I added a new folder:
1. This proposal is not related to a simple vault contract
2. Integration tests assume that all the proposals before the latest proposal are executed on chain and only the latest proposal is simulated for running the tests. Also these integration tests are unrelated to the state diff proposal that I have created.

2024-08-06 20:04 UTC, anajuliabit submitted a review, later dismissed
LGTM

2024-08-13 05:58 UTC, ElliotFriedman commented on src/proposals/state-diff/StateDiffTimelockProposal_01.sol
> +}
files needs a lint and then it should be good to merge!

2024-08-21 16:51 UTC, ElliotFriedman approved these changes
LGTM!

2024-08-21 16:51 UTC, merged